/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrtk_pnrs1_ra54_2014_CalculateStatisticsNative */

#ifndef _Included_rtrtk_pnrs1_ra54_2014_CalculateStatisticsNative
#define _Included_rtrtk_pnrs1_ra54_2014_CalculateStatisticsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrtk_pnrs1_ra54_2014_CalculateStatisticsNative
 * Method:    getStatistic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_rtrtk_pnrs1_ra54_12014_CalculateStatisticsNative_getStatistic
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
